### PR TITLE
multi-download only loading last file in Chrome 65

### PR DESCRIPTION
**Pull request by jamnikr**

### CODE REVIEW

**Comment by kevva** [comment]
What is this fixing?

**Comment by boris-petrov** [comment]
@kevva - what the title says. `multi-download` does not work on Chrome 65. Issue https://github.com/sindresorhus/multi-download/issues/19.

**Comment by kevva** [comment]
Oh yeah, I mean, is resorting to the fallback function really a fix? Is there no way to fix the `a.click()` way?

**Comment by boris-petrov** [comment]
I agree this is probably not the best solution, but until a "real" one is found, this workaround works. This is a pretty major problem so a quick fix is needed I think.

**Comment by mariogillazaro** [comment]
Hello, could this be propagated to NPM? @jamnikr

**Pull request closed without merging**
