### PR TITLE
Fix check for iframe readystate to support IE

### PR DESCRIPTION
**Pull request by GPetrites**
I believe this change fixes the IE issue

### CODE REVIEW

**Comment by sindresorhus** [comment]
What issue does it fix and why do you believe it does?

**Comment by GPetrites** [comment]
Sorry.  This is my first pull request, and I'm still learning how to do them correctly...

This should fix issue #11.  While debugging, I noticed that in the fallback method the readystate in IE stayed at interactive. If I treated "interactive" the same as "complete", multiple download worked.  I also tested in Firefox and saw no adverse impact.

**Comment by sindresorhus** [comment]
What IE versions? Is this reproducible in Edge?

**Comment by GPetrites** [comment]
I was only able to test with IE 11.  Edge worked correctly both before and after the fix.  As did Chrome.

**Comment by sindresorhus** [comment]
Thank you and congrats on your first pull request! 🎉

**Pull request merged**
